### ISSUE TITLE
What problem will occur when disableLock: true in golibmc?

### ISSUE THREAD

**Issue by mosasiru** [douban/libmc#36]
I like golibmc because it implements SetMulti using "ignore" flag.

But this seems to be running in just one thread if default settings.
What will occur when `disableLock` is true? Is this client not thread(goroutine) safe like python client?

**Comment by mckelvin** [comment]
Hi @mosasiru ,

Thanks for your interest on libmc.
Basically, the client works in single thread mode. In go, if your initialize a client(`golibmc.Client`) in one thread/coroutine, but use it in another coroutine or multi coroutines, it becomes unsafe if `disableLock` is true. In other words, you should make sure `disableLock` is false (the default behaviour) when you're using single client instance in multi coroutines/threads.

If you want to make the best of coroutines feature in go-lang, it's advised to implement a coroutines pool (containing multi `golibmc.Client` instances) by yourself (PR is welcoming). In such a case, you may have a lock in the pool level already and there's no need to lock for a single  `golibmc.Client` instance. While implementing a pool, make sure you have limited client instances, otherwise it may lead to unexpected high memcached `curr_connections`.

**Comment by mosasiru** [comment]
Thank you @mckelvin !

I see that implementing connection pooling is recommended if performance is needed.
I will try to implement in my product firstly, and I would PR if it seems to be good.

**Comment by mckelvin** [comment]
@mosasiru Yes, that's the idea. I'm going to close the issue right now. Feel free to PR or file another issue about connection pooling if essential.
