### ISSUE TITLE
golibmc SetMulti panic nil point error

### ISSUE THREAD

**Issue by mosasiru** [douban/libmc#42]
SetMulti panic when memcached connection seems unstable.

`runtime error: invalid memory address or nil pointer dereference`
stack trace
`/home/ubuntu/.go_workspace/src/github.com/douban/libmc/golibmc/golibmc.go:464 in (*Client).SetMulti
`

https://github.com/douban/libmc/blob/master/src/golibmc.go#L464
I think `*results` is nullable, so null check may be needed.
https://github.com/douban/libmc/blob/master/src/Client.cpp#L81

**Comment by mckelvin** [comment]
The bug is introduced (by me 😭 ) in https://github.com/douban/libmc/commit/2be0ce21501e7cbb4201d05d205c895994a25d9d#diff-28d9b0fb9ad32686216c98f74a3c7363R286 and another commit somehow I can't find it:

```diff
-	for i := 0; i <= int(n); i++ {
+	for i := 0; i < int(n); i++ {
```

Where `n` is the size of the result. `i < int(n)` should be used here.

* * *

@youngsofun There are some test cases for corner case in https://github.com/douban/libmc/tree/master/tests/shabby but all of them are for Python currently. Bug in this case should be found earlier if corresponding test cases for go are added.

**Comment by youngsofun** [comment]
@mckelvin  ok，I will do it later.
