### ISSUE TITLE
golibmc: Is there any problems setting 0 to MC_RETRY_TIMEOUT?

### ISSUE THREAD

**Issue by jumpeiMano** [douban/libmc#81]
Now, I set `1` which is the smallest value which can be set, but I would like to set it with `0` if possible. But now [I can't](https://github.com/douban/libmc/blob/master/src/golibmc.go#L349).
Do you have any problems? If there are no particular problems, I will create a pull request from now on.

Thanks!

**Comment by mckelvin** [comment]
Hey @jumpeiMano ,
Could you please describe your original requirement about why you'd like to set the `MC_RETRY_TIMEOUT` to `0`? This options will affect the variable named `m_deadUntil` in https://github.com/douban/libmc/blob/master/src/Connection.cpp . If that's always `0`, the client will try to reconnect without waiting, which is not a friendly behavior to the server side.


When a connection is `disconnected` due to some network error (`conn->markDead(reason)`), the libmc will try to connect without any delay(`delay=0` is passed in `markDead(...)`), but if that fails again, the connection will starting using the `MC_RETRY_TIMEOUT` feature by waiting for a few seconds(`delay>0`) before reconnecting to servers. For most of the cases, I think it's reasonable to have MC_RETRY_TIMEOUT > 0.

Please let me know if you have any other concern.

Regards,
Kelvin

**Comment by jumpeiMano** [comment]
Thank you for your response, @mckelvin !

I'm using your library on a system running on API of our service. Sometimes a large number of requests may come in a short time. At that time, it tries to create a new one when the number of the [`freeConns`](https://github.com/douban/libmc/blob/3798ce0af2ca0c9de5f3e670caa81dd1981b1cac/src/golibmc.go#L121) is insufficient, but it seems that there are more cases of connection failure.

I know that the retry timeout is not a memcached server side friendly behavior. However, the load of the current memcached server is not particularly problematic, and waiting for a long retry timeout is more problematic on the client side.

Initially, I thought that it would be better to set MC_RETRY_TIMEOUT in milliseconds. However, since [`t_time`](https://github.com/douban/libmc/blob/3798ce0af2ca0c9de5f3e670caa81dd1981b1cac/src/Connection.cpp#L167) is currently used within the [`tryReconnect`](https://github.com/douban/libmc/blob/3798ce0af2ca0c9de5f3e670caa81dd1981b1cac/src/Connection.cpp#L165-L183) function, I thought that it was difficult to fix it, so I thought it would be nice to be able to set 0.

How do you think about it?

**Comment by ariesdevil** [comment]
Hi @jumpeiMano ,PR is welcome if you are available. Otherwise, we will support it as soon.

**Comment by jumpeiMano** [comment]
Thanks @mckelvin @ariesdevil !
Could you review this PR, please?
https://github.com/douban/libmc/pull/82
